name: Django CI/CD
'on': null
push: null
branches:
  - main
pull_request:
  branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
          cache-dependency-path: requirements.txt
      - name: Verify requirements.txt exists
        run: >
          ls -la

          if [ -f requirements.txt ]; then cat requirements.txt; else echo
          "Error: requirements.txt not found"; exit 1; fi
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: List Installed Packages
        run: |
          pip list
      - name: Apply Migrations
        run: |
          python manage.py makemigrations --check
          python manage.py migrate
      - name: Run Tests
        run: |
          python manage.py test
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.EC2_HOST }}'
          username: '${{ secrets.EC2_USER }}'
          key: '${{ secrets.EC2_SSH_KEY }}'
          port: 22
          timeout: 60s
          debug: true
          script: |
            echo "Deploying to ${{ secrets.EC2_HOST }}"
            whoami
            cd ~/myproject
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
            sudo journalctl -u gunicorn -n 50 --no-pager
            sudo journalctl -u nginx -n 50 --no-pager

